    echo Arret des serveurs existants sur les ports 3000 et 3001...
    for /f "tokens=5" %%a in ('netstat -ano ^| findstr ":3000 " ^| findstr "LISTENING"') do taskkill /PID %%a /F 2>nul
    for /f "tokens=5" %%a in ('netstat -ano ^| findstr ":3001 " ^| findstr "LISTENING"') do taskkill /PID %%a /F 2>nul
    timeout /t 1 /nobreak >nul

    echo 1. Starting Backend...
    start "1. Sockets" cmd /k "npm run socket"

    echo 2. Starting distant host...
    start "2. Ngrok" cmd /k "ngrok http 3000"

    echo 3. Clearing .next cache...
    if exist .next rd /s /q .next

    echo 4. Starting Frontend...
    start "3. Next.ts Frontend" cmd /k "npm run dev"
