    echo 1. Starting Backend...
    start "1. Sockets" cmd /k "npm run socket"
    
    echo 2. Starting distant host...
    start "2. Ngrok" cmd /k "ngrok http 3000"

    echo 3. Starting Frontend...
    start "3. Next.ts Frontend" cmd /k "npm run dev"